name: FreeCases
version: '${version}'
main: com.jodexindustries.freecases.bootstrap.FreeCasesPlugin
api-version: 1.16
depend:
  - DonateCase
softdepend:
  - PlaceholderAPI
permissions:
  freecases.reload:
    default: op
  freecases.use:
    default: true